site_name: TForge
theme:
    name: mkdocs
    highlightjs: true
    hljs_style: school-book
    hljs_languages:
        - delphi
nav:
    - Home: index.md
    - Classes:
#        - BigCardinal: classes/bigcardinal.md
#        - BigInteger: classes/biginteger.md
        - ByteArray: classes/bytearray.md
        - TCipher: classes/tcipher.md
        - TCRC: classes/tcrc.md
        - THash: classes/thash.md
        - THMAC: classes/thmac.md
        - TMont: classes/tmont.md
#    - About:
#        - Release Notes: about/release-notes.md
#        - Contributing: about/contributing.md
#        - License: about/license.md
use_directory_urls: false

